---
title: "RNA-Seq Practical Session"
author: "Akshay"
date: "`r Sys.Date()`" # this will render the current date
output: 
  html_document:
    toc: true # table of contents
    toc_float: true # floating table of contents
    number_sections: true # number sections in the document
    toc_depth: 3 # table of contents depth
    theme: united # theme of the document
    highlight: tango # highlighting style

  
---

```{r }
cacheInput=TRUE
```
# *Create a count matrix from Star Output*

```{r echo=TRUE, fig.align="center", fig.height=10, fig.width=10, message=FALSE, warning=FALSE, cache=cacheInput, dpi=1000}
# Path to the directory containing STAR results
starResults = "/Users/akshay/OneDrive - Universitaet Bern/PhD/Course-work/Aii's_course/RNA-Seq-Practical_Session/StarMap/"

# Define the specific suffix
suffix <- ".ReadsPerGene.out.tab"

# List all files with the specified suffix in the directory
files_with_suffix <- list.files(path = starResults, pattern = paste0(".*", suffix, "$"), full.names = TRUE)

# Initialize data frame with row names from the first file
raw_counts = data.frame(row.names = row.names(read.table(files_with_suffix[1], row.names = 1, skip = 4)))

# Iterate over each file with the specified suffix
for (sample in files_with_suffix) {
  # Read the current sample's table, skipping the first 4 lines
  sample_table = read.table(sample, row.names = 1, skip = 4)
  # Extract the sample name using regex and add counts to the data frame
  raw_counts[sub(".*/(sample_\\w+).*", "\\1", sample)] = sample_table[row.names(raw_counts), "V2"]
}

# Display the first few rows of raw_counts
head(raw_counts)
```


# *DESeq2 Analysis*
## *Load libraries*

```{r echo=TRUE, fig.align="center", fig.height=10, fig.width=10, message=FALSE, warning=FALSE, cache=cacheInput, dpi=1000}
library(DESeq2)
library(ggplot2) 
library(pheatmap) 
```

## *Create Metadata*

```{r echo=TRUE, fig.align="center", fig.height=10, fig.width=10, message=FALSE, warning=FALSE, cache=cacheInput, dpi=1000}
# note: levels let's us define the reference levels
treatment <- factor( c(rep("a",4), rep("b",4)), levels=c("a", "b") ) # creating factors for treatment
colData <- data.frame(treatment, row.names = colnames(raw_counts)) # creating column data
colData
```

## *creating the DESeq object*
```{r echo=TRUE, fig.align="center", fig.height=10, fig.width=10, message=FALSE, warning=FALSE, cache=cacheInput, dpi=1000}
dds <- DESeqDataSetFromMatrix(
  countData = raw_counts, colData = colData, 
  design = ~ treatment) 
dim(dds) 
```

## *Filter low count genes*

```{r echo=TRUE, fig.align="center", fig.height=10, fig.width=10, message=FALSE, warning=FALSE, cache=cacheInput, dpi=1000}
idx <- rowSums(counts(dds, normalized=FALSE) >= 1) >= 4 # filtering low count genes
dds.f <- dds[idx, ] 
dim(dds.f) 
```



## *Run DESeq*
```{r echo=TRUE, fig.align="center", fig.height=10, fig.width=10, message=FALSE, warning=FALSE, cache=cacheInput, dpi=1000}
dds.f <- DESeq(dds.f) 
```


## *PCA*
```{r echo=TRUE, fig.align="center", fig.height=8, fig.width=8, message=FALSE, warning=FALSE, cache=cacheInput, dpi=1000}
library(ggrepel)

vsd <- varianceStabilizingTransformation(dds.f, blind=TRUE ) # performing PCA plot of the samples
pcaData <- plotPCA(vsd, intgroup=c("treatment")) # creating PCA data
pcaData + theme_minimal() + 
  #geom_label(aes(x=PC1,y=PC2,label=name))
geom_label_repel(aes(x=PC1, y=PC2, label=name), box.padding = 0.5)
```



<!-- ## *DEA* -->
<!-- ```{r echo=TRUE, fig.align="center", fig.height=10, fig.width=10, message=FALSE, warning=FALSE, cache=cacheInput, dpi=1000} -->
<!-- res <- results(dds.f) # performing DEA -->
<!-- summary( res ) # summarizing the results -->
<!-- ``` -->

# *Without Outliers*

## *Remove the outliers*
```{r echo=TRUE, fig.align="center", fig.height=10, fig.width=10, message=FALSE, warning=FALSE, cache=cacheInput, dpi=1000}
raw_counts_no_outliers = raw_counts[ , !( colnames(raw_counts) %in% c('sample_a4','sample_b3') ) ] # filtering outliers

# Recreate metadata
treatment <- factor( c(rep("a",3), rep("b",3)), levels=c("a", "b") ) # creating factors for treatment
colData <- data.frame(treatment, row.names = colnames(raw_counts_no_outliers)) # creating column data
colData 
dds <- DESeqDataSetFromMatrix(
  countData = raw_counts_no_outliers, colData = colData, 
  design = ~ treatment) # creating DESeq data set without outliers
dim(dds) # calculating dimensions of the dataset
```

## *Filter low count genes*
```{r echo=TRUE, fig.align="center", fig.height=10, fig.width=10, message=FALSE, warning=FALSE, cache=cacheInput, dpi=1000}

idx <- rowSums(counts(dds, normalized=FALSE) >= 1) >= 3 
dds.f <- dds[idx, ] # filtering the dataset
dim(dds.f) # dimensions of the filtered dataset

dds.f <- DESeq(dds.f) # Rerun DESeq2
```
## *PCA*
```{r echo=TRUE, fig.align="center", fig.height=8, fig.width=8, message=FALSE, warning=FALSE, cache=cacheInput, dpi=1000}
vsd <- varianceStabilizingTransformation(dds.f, blind=TRUE ) # performing PCA plot of the samples
pcaData <- plotPCA(vsd, intgroup=c("treatment")) # creating PCA data
pcaData + 
  theme_minimal() + geom_label_repel(aes(x=PC1, y=PC2, label=name), box.padding = 0.5)
```


## *DEA*
```{r echo=TRUE, fig.align="center", fig.height=10, fig.width=10, message=FALSE, warning=FALSE, cache=cacheInput, dpi=1000}
# extracting results for the treatment versus control contrast
res <- results(dds.f) # extracting results
summary( res ) # summarizing the results
```


## *Volcano plot*
```{r echo=TRUE, fig.align="center", fig.height=8, fig.width=8, message=FALSE, warning=FALSE, cache=cacheInput, dpi=1000}

FDRthreshold = 0.01 # setting FDR threshold
logFCthreshold = 1.0 # setting logFC threshold

# add a column of NAs
res.lfc <- lfcShrink(dds.f, coef=2, res=res)
res.lfc$diffexpressed <- "NO"

# if log2Foldchange > 1 and pvalue < 0.01, set as "UP" 
res.lfc$diffexpressed[res.lfc$log2FoldChange > logFCthreshold & res.lfc$padj < FDRthreshold] <- "UP"

# if log2Foldchange < 1 and pvalue < 0.01, set as "DOWN"
res.lfc$diffexpressed[res.lfc$log2FoldChange < -logFCthreshold & res.lfc$padj < FDRthreshold] <- "DOWN"

ggplot( data = data.frame( res.lfc ) , aes( x=log2FoldChange , y = -log10(padj) , col =diffexpressed ) ) + 
  geom_point() + 
  geom_vline(xintercept=c(-logFCthreshold, logFCthreshold), col="red") +
  geom_hline(yintercept=-log10(FDRthreshold), col="red") + 
  theme_minimal()+
  scale_color_manual(values=c("blue", "grey", "red")) # creating volcano plot
```

## *Heatmap*
```{r echo=TRUE, fig.align="center", fig.height=8, fig.width=8, message=FALSE, warning=FALSE, cache=cacheInput,dpi=1000}
vsd.counts <- assay(vsd)
topVarGenes <- head(order(rowVars(vsd.counts), decreasing = TRUE), 20)
mat  <- vsd.counts[ topVarGenes, ] #scaled counts of the top genes
mat  <- mat - rowMeans(mat)  # centering
pheatmap(mat) # creating heatmap
```
